//! Build script: slurp all `*.toml` files under `../../profiles` and emit a
//! generated Rust module `bundled.rs` that exposes them as `&'static str`.
//!
//! This lets us ship bundled profiles as compile-time resources with zero
//! runtime file-system coupling.

use std::fs;
use std::path::PathBuf;
use walkdir::WalkDir;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let profiles_root = manifest_dir.join("..").join("..").join("profiles");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("bundled.rs");

    let mut entries: Vec<(String, String)> = Vec::new();
    if profiles_root.is_dir() {
        for entry in WalkDir::new(&profiles_root).into_iter().filter_map(|e| e.ok()) {
            if !entry.file_type().is_file() {
                continue;
            }
            if entry.path().extension().and_then(|e| e.to_str()) != Some("toml") {
                continue;
            }
            let rel = entry
                .path()
                .strip_prefix(&profiles_root)
                .unwrap_or(entry.path())
                .to_string_lossy()
                .replace('\\', "/");
            let contents = fs::read_to_string(entry.path()).expect("read profile toml");
            entries.push((rel, contents));
            println!("cargo:rerun-if-changed={}", entry.path().display());
        }
    }
    println!("cargo:rerun-if-changed={}", profiles_root.display());

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit.\n");
    code.push_str("pub const BUNDLED: &[(&str, &str)] = &[\n");
    for (name, body) in &entries {
        code.push_str(&format!(
            "    ({:?}, r####\"{}\"####),\n",
            name,
            escape_raw(body)
        ));
    }
    code.push_str("];\n");

    fs::write(&out_path, code).expect("write bundled.rs");
}

/// Close any accidental `"####` in the body. For our TOML files this should
/// never occur; use a guard anyway.
fn escape_raw(s: &str) -> String {
    s.replace("\"####", "\"####_")
}
